# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\workspace\python\pyqt\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Interface(object):
    def setupUi(self, Interface):
        Interface.setObjectName("Interface")
        Interface.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Interface)
        self.centralwidget.setObjectName("centralwidget")
        self.tv_interfaces = QtWidgets.QTableView(self.centralwidget)
        self.tv_interfaces.setGeometry(QtCore.QRect(30, 140, 741, 192))
        self.tv_interfaces.setObjectName("tv_interfaces")
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setGeometry(QtCore.QRect(640, 70, 71, 31))
        self.btn_search.setObjectName("btn_search")
        self.btn_import = QtWidgets.QPushButton(self.centralwidget)
        self.btn_import.setGeometry(QtCore.QRect(540, 70, 71, 31))
        self.btn_import.setObjectName("btn_import")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(540, 20, 71, 31))
        self.btn_add.setObjectName("btn_add")
        self.le_interName = QtWidgets.QLineEdit(self.centralwidget)
        self.le_interName.setGeometry(QtCore.QRect(130, 20, 251, 31))
        self.le_interName.setObjectName("le_interName")
        self.lb_interName = QtWidgets.QLabel(self.centralwidget)
        self.lb_interName.setGeometry(QtCore.QRect(40, 20, 71, 31))
        self.lb_interName.setObjectName("lb_interName")
        self.lb_addr = QtWidgets.QLabel(self.centralwidget)
        self.lb_addr.setGeometry(QtCore.QRect(40, 80, 71, 21))
        self.lb_addr.setObjectName("lb_addr")
        self.le_addr = QtWidgets.QLineEdit(self.centralwidget)
        self.le_addr.setGeometry(QtCore.QRect(130, 70, 251, 31))
        self.le_addr.setObjectName("le_addr")
        Interface.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Interface)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        Interface.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Interface)
        self.statusbar.setObjectName("statusbar")
        Interface.setStatusBar(self.statusbar)

        self.retranslateUi(Interface)
        QtCore.QMetaObject.connectSlotsByName(Interface)

    def retranslateUi(self, Interface):
        _translate = QtCore.QCoreApplication.translate
        Interface.setWindowTitle(_translate("Interface", "MainWindow"))
        self.btn_search.setText(_translate("Interface", "查询"))
        self.btn_import.setText(_translate("Interface", "导入"))
        self.btn_add.setText(_translate("Interface", "录入"))
        self.lb_interName.setText(_translate("Interface", "接口名称"))
        self.lb_addr.setText(_translate("Interface", "接口地址"))
